spring.application.name=email-writer-sb

groq.api.key=${GROQ_API_KEY}

spring.datasource.url=jdbc:mysql://localhost:3306/emipi_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=1111_Bholu_
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

app.jwt.secret=MySuperSecretKeyThatIsAtLeast32CharactersLong123
app.jwt.expiration=86400000

app.cors.allowed-origins=http://localhost:5173

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true